### ISSUE TITLE
Ipad 3 downgrade error connecting to ssh connection refused.

### ISSUE THREAD

**Issue by hikaru78** [LukeZGD/iOS-OTA-Downgrader#43]
cant connect via ssh

noticed it doesn't ask me for an ip
ip is 127.0.0.1 port 2222

have deleted known hosts

Running ubuntu 20.04 liveusb

**Comment by LukeZGD** [comment]
Terminal output? The script won't ask for an IP address anymore because it uses SSH through USB instead of network.

**Comment by hikaru78** [comment]
******* iOS-OTA-Downgrader *******
   Downgrader script by LukeZGD   

[Log] Updating firmware...
[Log] Updating ipwndfu...
* Platform: linux
* HardwareModel: k93ap
* ProductType: iPad2,1
* ProductVersion: 9.3.5
* UniqueChipID (ECID): 657801534730

*** Main Menu ***
[Input] Select an option:
1) Downgrade device		 4) (Re-)Install Dependencies
2) Save OTA blobs		 5) (Any other key to exit)
3) Just put device in kDFU mode
#? 1
[Input] Select iOS version:
1) iOS 8.4.1		    3) Other
2) iOS 6.1.3		    4) (Any other key to exit)
#? 2
[Log] Option: Downgrade
[Log] Saving 6.1.3 blobs with tsschecker...
Version: 62d2b32f782e2735c859ab4f51976461b555e505 - 360
[TSSC] manually specified ECID to use, parsed "657801534730" to dec:657801534730 hex:992806dd0a
[TSSC] opening resources/manifests/BuildManifest_iPad2,1_6.1.3.plist
[WARNING] [TSSC] could not get id0 for installType=Erase. Using fallback installType=Update since user did not specify installType manually
[TSSR] LOG: device iPad2,1 doesn't need a baseband ticket, continuing without requesting a Baseband ticket
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[Error] [TSSR] Error: could not get id0 for installType=Erase
Saved signing tickets!

iOS 6.1.3 for device iPad2,1 IS being signed!
[Log] Successfully saved 6.1.3 blobs.
[Log] Verifying IPSW...
[Log] Decrypting iBSS...
[Log] IV = 781b9672a86ba1b41f8b7fa0af714c94
[Log] Key = bbd7bf676dbcc6ba93c76d496b7af39ae7772eaaad2ec9fb71dc1fd004827784
/home/tihm/odysseusOTA/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 29f334087f5439f6c8d62b4f6c93cee85b039792417ee3294ca2233b3e27f1da88e22c1916ec12df89cc8662f009e8f6
[Log] Patching iBSS...
* Make sure OpenSSH/Dropbear is installed on the device!
[Log] Copying stuff to device via SSH...
* (Enter root password of your iOS device when prompted, default is 'alpine')
ssh: connect to host 127.0.0.1 port 2222: Connection refused
lost connection

[Error] Cannot connect to device via SSH.
* Please check your ~/.ssh/known_hosts file and try again

ubuntu@ubuntu:~/IOS-OTA-Downgrader$

**Comment by hikaru78** [comment]
this is my ipad 3

both running 9.3x

jailbroken via phoenix

can ssh via ip 

******* iOS-OTA-Downgrader *******
   Downgrader script by LukeZGD   

[Log] Updating firmware...
[Log] Updating ipwndfu...
* Platform: linux
* HardwareModel: j2ap
* ProductType: iPad3,2
* ProductVersion: 9.3.6
* UniqueChipID (ECID): 3825340530120

*** Main Menu ***
[Input] Select an option:
1) Downgrade device		 4) (Re-)Install Dependencies
2) Save OTA blobs		 5) (Any other key to exit)
3) Just put device in kDFU mode
#? 1
[Input] Select iOS version:
1) iOS 8.4.1		    3) (Any other key to exit)
2) Other
#? 1
[Log] Option: Downgrade
[Log] Saving 8.4.1 blobs with tsschecker...
Version: 62d2b32f782e2735c859ab4f51976461b555e505 - 360
[TSSC] manually specified ECID to use, parsed "3825340530120" to dec:3825340530120 hex:37aa8103dc8
[TSSC] opening resources/manifests/BuildManifest_iPad3,2_8.4.1.plist
[WARNING] [TSSC] could not get id0 for installType=Erase. Using fallback installType=Update since user did not specify installType manually
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[Error] [TSSR] Error: could not get id0 for installType=Erase
Saved signing tickets!

iOS 8.4.1 for device iPad3,2 IS being signed!
[Log] Successfully saved 8.4.1 blobs.
[Log] Verifying IPSW...
[Log] Extracting iBSS from IPSW...
Archive:  iPad3,2_8.4.1_12H321_Restore.ipsw
  inflating: saved/iPad3,2/iBSS.j2.RELEASE.dfu  
[Log] Decrypting iBSS...
[Log] IV = 32fcd912cb9a472ef2a6db72596ae01c
[Log] Key = 076720d5a07e8011bdda6f6eafaf4845b40a441615cd1d7c1a9cca438ce7db17
/home/tihm/odysseusOTA/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: a40b3d8f62945a12480a15b533acbe1a7b14e51fe34e03e06aabf337aa7cfc1bd89630f75f314d2060af8669e9c18a99
[Log] Patching iBSS...
* Make sure OpenSSH/Dropbear is installed on the device!
[Log] Copying stuff to device via SSH...
* (Enter root password of your iOS device when prompted, default is 'alpine')
ssh: connect to host 127.0.0.1 port 2222: Connection refused
lost connection

[Error] Cannot connect to device via SSH.
* Please check your ~/.ssh/known_hosts file and try again

ubuntu@ubuntu:~/IOS-OTA-Downgrader$

**Comment by LukeZGD** [comment]
Please try again with the latest commit, should fix things now

**Comment by ksvoboda** [comment]
Hi,
I have the same issue, tried downloading it againg to be sure I have the newest version but I cannot connect to device via SSH. I am running MacOS Catalina  nad trying to downgrade iPad 2. I have Jailbreaked iPad and installed OpenSSH

`krystofsvoboda@MacBook-Pro iOS-OTA-Downgrader-master 2 % ./restore.sh

******* iOS-OTA-Downgrader *******
   Downgrader script by LukeZGD   

cat: resources/firmware/iPad2,2/13G36/url: No such file or directory
[Log] Downloading firmware...
[Log] Downloading ipwndfu...
* Platform: macos
* HardwareModel: k94ap
* ProductType: iPad2,2
* ProductVersion: 9.3.5
* UniqueChipID (ECID): 3067144236300

*** Main Menu ***
[Input] Select an option:
1) Downgrade device		 4) (Re-)Install Dependencies
2) Save OTA blobs		 5) (Any other key to exit)
3) Just put device in kDFU mode
#? 1
[Input] Select iOS version:
1) iOS 8.4.1		    3) Other
2) iOS 6.1.3		    4) (Any other key to exit)
#? 2
[Log] Option: Downgrade
[Log] Saving 6.1.3 blobs with tsschecker...
Version: b9d193aa6e6d24421094873c830692d02d8b32f5 - 304
libfragmentzip version: 0.59-542a470d7be248681dba71d0f04e7dc8c2718b73
[TSSC] manually specified ECID to use, parsed "3067144236300" to dec:3067144236300 hex:2ca200aed0c
[TSSC] opening resources/manifests/BuildManifest_iPad2,2_6.1.3.plist
[WARNING] [TSSC] could not get id0 for installType=Erase. Using fallback installType=Update since user did not specify installType manually
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[Error] [TSSR] Error: could not get id0 for installType=Erase
Saved shsh blobs!

iOS 6.1.3 for device iPad2,2 IS being signed!
[Log] Successfully saved 6.1.3 blobs.
[Log] iOS 6.1.3 IPSW cannot be found. Downloading IPSW...
cat: resources/firmware/iPad2,2/10B329/url: No such file or directory
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
mv: rename tmp/iPad2,2_6.1.3_10B329_Restore.ipsw to ./iPad2,2_6.1.3_10B329_Restore.ipsw: No such file or directory
[Log] Verifying IPSW...
cat: resources/firmware/iPad2,2/10B329/sha1sum: No such file or directory
shasum: iPad2,2_6.1.3_10B329_Restore.ipsw: 
[Log] Downloading iBSS...
cat: resources/firmware/iPad2,2/12H321/url: No such file or directory
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
Error: url required!
mv: rename iBSS.k94.RELEASE.dfu to saved/iPad2,2/iBSS.k94.RELEASE.dfu: No such file or directory
[Log] Decrypting iBSS...
[Log] IV = 
[Log] Key = 
error: cannot open infile
[Log] Patching iBSS...
bspatch: tmp/iBSS.dec: No such file or directory
Creating listening port 2222 for device port 22
bind(): Address already in use
Error creating socket for listen port 2222: Address already in use
* Make sure OpenSSH/Dropbear is installed on the device!
[Log] Copying stuff to device via SSH...
* (Enter root password of your iOS device when prompted, default is 'alpine')
New connection for 2222->22, fd = 5
waiting for connection
Requesting connecion to USB device handle 25 (serial: aad4d9603a3bf1a47aecb7ee0b2295e318587634), port 22
root@127.0.0.1's password: 
kloader                                       100%   51KB   3.7MB/s   00:00    
tmp/pwnediBSS: No such file or directory
pwn.sh                                        100%   44     8.0KB/s   00:00    

[Error] Cannot connect to device via SSH.
* Please check your ~/.ssh/known_hosts file and try again`

Thanks for help

**Comment by LukeZGD** [comment]
> Hi,
> I have the same issue, tried downloading it againg to be sure I have the newest version but I cannot connect to device via SSH. I am running MacOS Catalina nad trying to downgrade iPad 2. I have Jailbreaked iPad and installed OpenSSH
> 
> krystofsvoboda@MacBook-Pro iOS-OTA-Downgrader-master 2 % ./restore.sh
> 
> ******* iOS-OTA-Downgrader *******
> Downgrader script by LukeZGD
> 
> cat: resources/firmware/iPad2,2/13G36/url: No such file or directory
> [Log] Downloading firmware...
> [Log] Downloading ipwndfu...
> 
>     * Platform: macos
> 
>     * HardwareModel: k94ap
> 
>     * ProductType: iPad2,2
> 
>     * ProductVersion: 9.3.5
> 
>     * UniqueChipID (ECID): 3067144236300
> 
> 
> *** Main Menu ***
> [Input] Select an option:
> 
>     1. Downgrade device		 4) (Re-)Install Dependencies
> 
>     2. Save OTA blobs		 5) (Any other key to exit)
> 
>     3. Just put device in kDFU mode
>        #? 1
>        [Input] Select iOS version:
> 
>     4. iOS 8.4.1		    3) Other
> 
>     5. iOS 6.1.3		    4) (Any other key to exit)
>        #? 2
>        [Log] Option: Downgrade
>        [Log] Saving 6.1.3 blobs with tsschecker...
>        Version: b9d193aa6e6d24421094873c830692d02d8b32f5 - 304
>        libfragmentzip version: 0.59-542a470d7be248681dba71d0f04e7dc8c2718b73
>        [TSSC] manually specified ECID to use, parsed "3067144236300" to dec:3067144236300 hex:2ca200aed0c
>        [TSSC] opening resources/manifests/BuildManifest_iPad2,2_6.1.3.plist
>        [WARNING] [TSSC] could not get id0 for installType=Erase. Using fallback installType=Update since user did not specify installType manually
>        [TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
>        [TSSR] Sending TSS request attempt 1... success
>        [Error] [TSSR] Error: could not get id0 for installType=Erase
>        Saved shsh blobs!
> 
> 
> iOS 6.1.3 for device iPad2,2 IS being signed!
> [Log] Successfully saved 6.1.3 blobs.
> [Log] iOS 6.1.3 IPSW cannot be found. Downloading IPSW...
> cat: resources/firmware/iPad2,2/10B329/url: No such file or directory
> curl: no URL specified!
> curl: try 'curl --help' or 'curl --manual' for more information
> mv: rename tmp/iPad2,2_6.1.3_10B329_Restore.ipsw to ./iPad2,2_6.1.3_10B329_Restore.ipsw: No such file or directory
> [Log] Verifying IPSW...
> cat: resources/firmware/iPad2,2/10B329/sha1sum: No such file or directory
> shasum: iPad2,2_6.1.3_10B329_Restore.ipsw:
> [Log] Downloading iBSS...
> cat: resources/firmware/iPad2,2/12H321/url: No such file or directory
> Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
> libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
> Error: url required!
> mv: rename iBSS.k94.RELEASE.dfu to saved/iPad2,2/iBSS.k94.RELEASE.dfu: No such file or directory
> [Log] Decrypting iBSS...
> [Log] IV =
> [Log] Key =
> error: cannot open infile
> [Log] Patching iBSS...
> bspatch: tmp/iBSS.dec: No such file or directory
> Creating listening port 2222 for device port 22
> bind(): Address already in use
> Error creating socket for listen port 2222: Address already in use
> 
>     * Make sure OpenSSH/Dropbear is installed on the device!
>       [Log] Copying stuff to device via SSH...
> 
>     * (Enter root password of your iOS device when prompted, default is 'alpine')
>       New connection for 2222->22, fd = 5
>       waiting for connection
>       Requesting connecion to USB device handle 25 (serial: aad4d9603a3bf1a47aecb7ee0b2295e318587634), port 22
>       root@127.0.0.1's password:
>       kloader                                       100%   51KB   3.7MB/s   00:00
>       tmp/pwnediBSS: No such file or directory
>       pwn.sh                                        100%   44     8.0KB/s   00:00
> 
> 
> [Error] Cannot connect to device via SSH.
> 
>     * Please check your ~/.ssh/known_hosts file and try again
> 
> 
> Thanks for help

Should be fixed by the latest commit

**Comment by hikaru78** [comment]
can confirm is working now on ubunto 20.04
i will test on high sierra and advise

im sure im not very good at this but i suspect this would cause an issue

cat: resources/firmware/iPad2,2/10B329/url: No such file or directory
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
mv: rename tmp/iPad2,2_6.1.3_10B329_Restore.ipsw to ./iPad2,2_6.1.3_10B329_Restore.ipsw: No such file or directory
[Log] Verifying IPSW...
cat: resources/firmware/iPad2,2/10B329/sha1sum: No such file or directory
shasum: iPad2,2_6.1.3_10B329_Restore.ipsw:

**Comment by tamarindmonkey** [comment]
Still broken for Catalina. I will add an issue and create a push. Missing: AddKeysToAgent yes
